### ISSUE TITLE
question - when using buffer mode, what are the contents of the buffer

### ISSUE THREAD

**Issue by juggledad** [O-Hahn/node-red-contrib-camerapi#20]
In buffer mode - what is in the buffer? 

I'm trying to feed the image directly to the ui-dashboard so I fed the buffer to the node-red-node-base64 and I see all sorts of 'stuff' that is not the image by itself. IHere is the begining of the buffer:
����c�Exif��MM�*����
�������@��������������������
��������������������(�������2����������������i�����������RaspberryPi�RP_ov5647����H������H���2018:07:11 17:26:00����������ڂ��������"��������'�������������0220�����������������������
��������������
�����"�������*���������	���������
������2�|���4��:������0100���������������@���������������n�������������������������B@��q8��'2018:07:11 17:26:00�2018:07:11 17:26:00��;�w�B@��w���'�������d��w���'������'ev=-1 mlux=-1 exp=66452 ag=1088 focus=255 gain_r=1.000 gain_b=1.000 greenness=0 ccm=0,0,0,0,0,0,0,0,0,0,0,0 md=0 tg=303 303 oth=0 0 b=0 f=303 303 fi=0 ISP Build Date: Jun 29 2018, 13:16:30 VC_BUILD_ID_VERSION: 97765855d9ae607d0e678171cf9d83b218f237dd (clean) VC_BUILD_ID_USER: dc4 VC_BUILD_ID_BRANCH: master ������R98��������������@�������0���������������������(��������������������`��������H������H����������	


		
is there a way to grab only the image part of the buffer?

**Comment by O-Hahn** [comment]
when using the buffer mode - the buffer contains the same content as the file because i am usining the stored temp file from the picam alsways as the source. if you want to stream directly to the dashborad - you can use the buffer mode and send it to a template which includes the img tag... - i am using it that way - but do before a conversion to base64 in the flow.
i do not add any metadata or a seperate header.
